### ISSUE TITLE
Unhandled Promise rejection on close()

### ISSUE THREAD

**Issue by murrayju** [Yaffle/EventSource#133]
When calling `es.close()`, the internal `fetch` promise is aborted. Because there is no `.catch()` case in the promise chain (and the promise is not exposed for the consumer to handle), this results in the browser's `unhandledrejection` event being raised.

This was revealed through some react dev tool, which renders unhandled rejections on the screen:
![image](https://user-images.githubusercontent.com/508461/62719526-6c689580-b9c5-11e9-9767-581a599876c7.png)

**Comment by Yaffle** [comment]
This was fixed in 1.0.7, seems, https://github.com/Yaffle/EventSource/commit/5eb75b8a40153c9477855c45ae000530f1842417

**Comment by murrayju** [comment]
No, I'm already running 1.0.7. That change added a `catch` for the inner promise (for `reader.read()`). The problem here is the outer promise, of the `fetch` call itself.

**Comment by murrayju** [comment]
This isn't as straightforward as I first thought... the `fetch` call has a `finally`, which should be catching the rejection. Adding an extra `catch` made no difference in my tests.

I've managed to reproduce the unhandled rejection though in an [isolated codepen](https://codepen.io/murrayju/pen/eqrXKJ). It only seems to happen if I call `es.close()` before the `open` event fires. If I instead wait to call it until later, it seems to work properly. Maybe this is a clue, but this doesn't agree with what I'm seeing in my react app.

Note: this uses [runkit to provide a test SSE server](https://runkit.com/murrayju/runkit-npm-sse-channel).

**Comment by Yaffle** [comment]
@murrayju 
https://github.com/Yaffle/EventSource/commit/d6a56711436bc6c48f845c303a8f49e217064413

**Comment by murrayju** [comment]
Those code changes look solid to me, however I'm still seeing the issue in my app when pulling in this code.

It seems like some sort of race condition. I managed to reproduce it by setting up react in [this codepen](https://codepen.io/murrayju/pen/KOxyex). I let it run for several minutes, and saw the `unhandledrejection` fire once.

Inexplicably, in my app, the `close()` is only called when navigating away from the page (when the react component is unmounted), but the `unhandledrejection` happens every time.

**Comment by murrayju** [comment]
Also, this might only happen in Firefox... I can't reproduce it with the new code in Chrome.

**Comment by Yaffle** [comment]
@murrayju , https://github.com/Yaffle/EventSource/commit/e721878f06f21f0de671b7f6f31cc10eeb66de76

**Comment by murrayju** [comment]
Confirmed that this is now fixed for me on Firefox. Thanks @Yaffle!
